# Generated by Django 4.0.4 on 2022-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoAPI', '0002_alter_coworking_work_alter_historicalcoworking_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
